source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'

# Database
gem "pg", "~> 0.15"

# Enum-like attribute
gem "enumerize", "~> 0.6.1"

# Use HAML for markup
gem "haml", "~> 4.0.4"

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use YUI as compressor for CSS assets
gem 'yui-compressor'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

# Strip whitespace and convert "" -> nil on model validation
gem "strip_attributes", "~> 1.4"

# SASS version of Bootstrap
gem "bootstrap-sass", "~> 2.2.2.0"

# Pretty fonts
gem "font-awesome-sass-rails", "~> 3.0.0"

# Javascript date-picker
gem "bootstrap-datepicker-rails", "~> 1.1.0"

gem "thin"

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :production do
  gem 'rails_12factor'
end
